name: buddyexpense
description: 'Seamlessly manage shared expenses and settle up with friends through BuddyExpense, your smart solution for hassle-free group finance.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: 0.68.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  permission_handler: ^12.0.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  animate_do: ^4.2.0
  pin_code_fields: ^8.0.1
  animated_text_kit: ^4.2.3
  page_transition: ^2.2.1
  google_sign_in: '>=7.1.1'
  firebase_auth: '>=6.0.1'
  firebase_core: '>=4.0.0'
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'
  remove_alpha_ios: true
